name: Take screenshot of the page

on: deployment_status

jobs:
  screenshot:
    if: github.event.deployment_status.state == 'success'
    name: Screenshot
    runs-on: ubuntu-latest

    steps:

    - name: Screenshot
      uses: swinton/screenshot-website@v1.x
      with:
        source: https://yumiizumi.com/
        destination: screenshot.png
        full-page: true
    
    - name: Upload screenshot
      uses: actions/upload-artifact@v3
      with:
        name: screenshot
        path: screenshot.png